### ISSUE TITLE
docs: how to deploy frontend

### ISSUE THREAD

**Issue by chamthesleeptalker** [ausome-maps/TherapEase#10]
- Study Nuxt app deployment

**Comment by lkpanganiban** [comment]
To implement a deployment, the following steps must be done:
- **build**: execute `npm run generate`. This will produce a `.output` folder containing the `public` and `server` directories.
- **deploy**: copy the contents of the `.output/public` folder and save it into the an e.g. Nginx

Environment variables for Nuxt can be set using the following workflow:  https://nuxt.com/docs/guide/going-further/runtime-config. 

![image](https://github.com/ausome-maps/TherapEase/assets/6139863/10dc6627-4d2f-40fe-87f5-adb8228bbfb7)
