### ISSUE TITLE
storage service

### ISSUE THREAD

**Issue by lkpanganiban** [ausome-maps/TherapEase#32]
To properly manage the images that are uploaded, a storage service is essential for containerization and distribution purposes. We will have the following options:
### Cloud
- Digital Ocean Spaces $5/month/250 GB
- AWS, GCP, Azure
   
    ![image](https://github.com/ausome-maps/TherapEase/assets/6139863/53c2c0d4-2767-42f1-a144-42cae3041528)

### Self Hosted
- Nginx
- [Minio](https://min.io/)

Minio provides the best flexibility amongst the self hosted options since it can be a wrapper to other cloud storage providers. This will require some development to configure and set this up.

## Workflow
1. Store/upload the image into the blob storage.
2. The container name can be the facility ID so we can properly trace the data.
3. Create a URL of the image (ensure that this can be accessed outside). Use incognito to check.
4. Copy and paste the URL to the images field in the Facility Properties.

Note: Ideally this needs to be automated in the data admin interface. Where the user will just upload the image and the links and urls will automatically be generated.

**Comment by chamthesleeptalker** [comment]
Maybe we can use Azure's free tier for this. I think 5GB is enough for now, since we are limiting images per entry to 3 images and we can set a file sizing limit as well. 

We can use ausomemaps or ausomeco email for the accounts.

**Comment by lkpanganiban** [comment]
We will be using MinIO as the main object storage service/system. 

![image](https://github.com/ausome-maps/TherapEase/assets/6139863/80de4eeb-eef3-4c1f-81cb-580b54222fc0)
