### ISSUE TITLE
Data loading the outputs from Kobo Toolbox

### ISSUE THREAD

**Issue by lkpanganiban** [ausome-maps/TherapEase#38]
Kobo toolbox is the main form of capturing information about the facilities. We will need to develop a pipeline or CLI to fetch and upload the data

**Comment by chamthesleeptalker** [comment]
The plan here to move the form to the platform itself to better enforce our data model.

**Comment by lkpanganiban** [comment]
This issue is closed since we will be using the script `utils/load_data.py` to store kobotoolbox data to the search database.
