### ISSUE TITLE
question: Facilities and Services Data

### ISSUE THREAD

**Issue by lkpanganiban** [ausome-maps/TherapEase#4]
The following are the data types that we have based on the origin/source.

1. **Form Submission Entries**: These contain various information like services offered, location, contact details, etc. This information was directly given by professionals and organizations who are offering such services.
2. **OSM Derived**: Facilities or services that came from OSM. These mostly contain information that came from databases from public repositories and organizations.

Question:
- Do we implement a direct link between 1 and 2? E.g. Adding an osm_id column in the data from submitted entries, where the lookup may be geospatial (if the point is < 5m? then we match these) or using the facility name.

**Comment by chamthesleeptalker** [comment]
*All centers, clinics, and schools needs to be POIs in OpenStreetMap. 
*OSM IDs should be included in the data schema

**Comment by chamthesleeptalker** [comment]
https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element
