### ISSUE TITLE
design: create balsamiq low-fidelity mockups

### ISSUE THREAD

**Issue by chamthesleeptalker** [ausome-maps/TherapEase#7]

**Comment by chamthesleeptalker** [comment]
@Chibogret Kindly add the balsamiq screens here. Thanks!

**Comment by Chibogret** [comment]
**Landing/Home Page** - This includes a listing with categories and a carousel section for raising awareness, promoting featured listings, and showcasing promotions.
![image](https://github.com/ausome-maps/TherapEase/assets/100111511/34fdcd65-595d-49cf-a035-c605f091907f)

**Search Page** - This displays the results based on the filters selected by the user. Ideally, both a list view and a grid view should be implemented.
![image](https://github.com/ausome-maps/TherapEase/assets/100111511/c64fdc9c-d391-42ad-b911-d24958fe46a0)

**Details Page** - This provides comprehensive information and details about a specific listing. It presents a detailed description, high-resolution images, key features, contact information, and any additional relevant information. 
![image](https://github.com/ausome-maps/TherapEase/assets/100111511/2092b467-c61b-47fa-ab96-8050b01128a9)
