### ISSUE TITLE
Other_services needs to be json

### ISSUE THREAD

**Issue by chamthesleeptalker** [ausome-maps/TherapEase#79]
Update data parsing for other_services
- data model requires JSON
- UI is splitting text with commas as delimiter

**Comment by lkpanganiban** [comment]
In the current admin interface, you can store the other_services as such

![image](https://github.com/ausome-maps/TherapEase/assets/6139863/a4289b6e-76da-4afd-844c-4e647553ab8f)

**Comment by chamthesleeptalker** [comment]
@lkpanganiban, from our data model,
![image](https://github.com/ausome-maps/TherapEase/assets/4580789/7999bb04-56b9-4974-bb95-8dfae1c76ba2)

**Comment by lkpanganiban** [comment]
For the backend/API side this is already supported. We will just need to update the actual data.
